version: "3"
services:
  app:
    user: "${UID:-4210986}:${GID:-4210986}"
    build:
      args:
        UID: ${UID:-4210986}
        GID: ${GID:-4210986}
        UNAME: ${USER:-filario}
      context: ../../
      dockerfile: .devcontainers/kind/Dockerfile
    working_dir: /sbo
    volumes:
      - ../../:/sbo
    environment:
      KUBECONFIG: /home/${USER}/.kube/config
      DOCKER_HOST: tcp://dind:2375
      OPERATOR_REPO_REF: registry:5000/sbo
    links:
      - dind
    depends_on:
      dind:
        condition: service_healthy
    command:
      - sleep
      - infinity

  dind:
    hostname: kubernetes
    image: docker:dind
    privileged: true
    environment:
      DOCKER_TLS_CERTDIR: ""
    expose:
    - 2375
    volumes:
      - ./docker-daemon.json:/etc/docker/daemon.json
    healthcheck:
      test: ["CMD-SHELL", "docker", "ps"]
      interval: 5s
      timeout: 5s
      retries: 10
    links:
      - registry

  registry:
    image: registry:2
    restart: always

