version: "3"
services:
  app:
    privileged: true
    build:
      args:
        UID: ${UID}
        GID: ${GID}
        UNAME: ${UNAME}
      context: ../../
      dockerfile: .devcontainers/minikube/Dockerfile
    working_dir: /sbo
    volumes:
      - ../../:/sbo
      - ./docker-daemon.json:/etc/docker/daemon.json
    environment:
      KUBECONFIG: /tmp/minikubeconfig
