== Remote Openshift

*Prerequisites*

* Openshift Cluster with _Administrator_ access

=== Using the internal Container Registry

1. Login into the Openshift's internal registry
+
[source,bash]
----
oc registry login --skip-check
----

2. Bake the image name
+
[source,bash]
----
export OPERATOR_IMAGE_REF=$(oc registry info)/service-binding-operator/controller:latest
----

3. Build and push the image
+
[source,bash]
----
make image push-image -o registry-login
----

4. Deploy the operator
+
[source,bash]
----
make deploy
----
NOTE: You may need to register the registry address (the result of `oc registry info`) as a insecure registry (in the `docker/daemon.json` file) and restart docker

5. Run acceptance tests tagged with `@dev` using `kubectl` CLI
+
[source,bash]
----
make test-acceptance TEST_ACCEPTANCE_TAGS="@dev" TEST_ACCEPTANCE_START_SBO=remote TEST_ACCEPTANCE_CLI=kubectl
----

6. Run acceptance tests for a single scenario
+
[source,bash]
----
make test-acceptance TEST_ACCEPTANCE_START_SBO=remote TEST_ACCEPTANCE_CLI=kubectl EXTRA_BEHAVE_ARGS='-n "Specify path of secret in the Service Binding"'
----


=== Using an external Container Registry

1. Follow the instructions at link:../release-to-cr/release-to-cr.html[Release to a Container Registry] to build and push the image.

2. Install the operator on the cluster using the same OPERATOR_REPO_REF used for building and pushing the image
+
[source,bash]
----
make deploy OPERATOR_REPO_REF=<SAME_OF_IMAGE_BUILD_AND_PUSH>
----

3. Run acceptance tests tagged with `@dev` using `kubectl` CLI
+
[source,bash]
----
make test-acceptance TEST_ACCEPTANCE_TAGS="@dev" TEST_ACCEPTANCE_START_SBO=remote TEST_ACCEPTANCE_CLI=kubectl
----

4. Run acceptance tests for a single scenario
+
[source,bash]
----
make test-acceptance TEST_ACCEPTANCE_START_SBO=remote TEST_ACCEPTANCE_CLI=kubectl EXTRA_BEHAVE_ARGS='-n "Specify path of secret in the Service Binding"'
----

